sonar.projectKey=Asad3746_Flask-Store-Api
sonar.organization=asad3746

sonar.sources=.
sonar.python.version=3.11

sonar.exclusions=**/__pycache__/**,**/venv/**,**/.venv/**,**/tests/**

# trigger sonar scan