name: CI + Postman Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Verify Node
        run: node -v

      - name: Install Newman and PostgreSQL client
        run: |
          npm install -g newman
          newman -v
          sudo apt-get install -y postgresql-client

      - name: Clean up test data before run
        run: |
          PGPASSWORD=X9jS1xOSEq7PImFZ4FCXxgz9KCmMJbHG psql \
            "postgresql://flask_store_db_mxcn_user@dpg-d8hdqvk2m8qs73b1qlvg-a.singapore-postgres.render.com/flask_store_db_mxcn" \
            -c "DELETE FROM carts WHERE user_id IN (7, 8, 9, 10);"
        env:
          PGPASSWORD: X9jS1xOSEq7PImFZ4FCXxgz9KCmMJbHG

      - name: Run Database Migrations (Flyway)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/flyway/migrations:/flyway/sql \
            flyway/flyway:latest \
            -url="jdbc:postgresql://dpg-d8hdqvk2m8qs73b1qlvg-a.singapore-postgres.render.com/flask_store_db_mxcn" \
            -user="flask_store_db_mxcn_user" \
            -password="X9jS1xOSEq7PImFZ4FCXxgz9KCmMJbHG" \
            -locations="filesystem:/flyway/sql" \
            migrate

      - name: Wait for Render API
        run: |
          echo "Checking API..."
          for i in {1..10}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://ecommerce-api-wks8.onrender.com || true)
            echo "Attempt $i: $STATUS"
            if [ "$STATUS" -eq 200 ] || [ "$STATUS" -eq 404 ]; then
              echo "API ready"
              break
            fi
            sleep 5
          done

      - name: Run Postman Tests
        run: |
          newman run postman_collection.json \
            -e postman_environment.json \
            --env-var "base_url=https://ecommerce-api-wks8.onrender.com" \
            --verbose \
            --reporters cli,junit \
            --reporter-junit-export results.xml

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: postman-report
          path: results.xml